set nocompatible              " 
filetype off                  " required by Vundle

" activates syntax highlighting among other things
syntax on

set t_Co=256

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'benmills/vimux'
Plugin 'bling/vim-airline'

" ===== ruby-specific =====
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-fugitive'

" =========================

" All of your Plugins must be added before the following line
call vundle#end() 

" activates filetype detection
filetype plugin indent on

set wildignore+=*/tmp/*,*.so,*.swp,*.zip
set tags+=gems.tags
let g:airline_powerline_fonts = 1
set laststatus=2
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"

let g:ctrlp_custom_ignore = {
  \ 'dir': '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(so\.?\d*)$'
  \ }
